from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dao/', views.dao, name='dao'),
    path('courses/', views.courses, name='courses'),
    path('user_course/', views.user_course, name='user_course'),
    path('about/', views.about, name='about'),
    path('verify-email/', views.verify_email, name='verify_email'),
    path('forgot_password/', views.forget_password, name='forget_password'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('add_course/', views.add_course, name='add_course'),
    path('add_proposal/',views.add_proposal, name='add_proposal'),
    path('dao/<int:proposal_id>/', views.proposal_detail, name='proposal_detail'),
    path('courses/<int:course_id>/', views.course_detail, name='course_detail'),
    path('courses/start/<int:course_id>/', views.start_course, name='start_course'),
    path('courses/complete/<int:course_id>/', views.complete_course, name='complete_course'),
    path('courses/edit_course/<int:course_id>/', views.edit_course, name='edit_course'),
    path('courses/<int:course_id>/episode/<int:episode_id>', views.episode_view, name='episode_view'),
    path('courses/<int:course_id>/episode/<int:episode_id>/save/', views.save_progress, name='save_progress'),
    path('courses/<int:course_id>/episode/<int:episode_id>/toggle_complete/', views.toggle_complete, name='toggle_complete'),
    path('update-profile-image/', views.update_profile_image, name='update_profile_image'),
    path('courses/search/', views.Search, name='search'),
    path('chat/', views.send_message, name='chat'),
    path('courses/quiz/<int:courseid>/', views.Technical_quiz, name='quiz_view'),
    path('generate/', views.generate_wallet, name='generate'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('get_subscribed/<str:plan>', views.get_subscribe, name='get_subscribed'),
    path('wallet/', views.wallet, name='wallet'),
    path('reward/', views.reward, name='reward'),
    path('wallet/send/init/', views.send_init_view, name='send_init'),
    path('wallet/send/confirm/', views.send_confirm_view, name='send_confirm'),
    path('wallet/export/init/', views.export_init_view, name='export_init'),
    path("wallet/export/confirm/", views.export_confirm_view, name='export_confirm'),
    path('courses/comment/<int:course_id>/<int:episode_id>/', views.add_comment, name='add_comment'),
    path('comment/reply/<int:comment_id>/', views.add_reply, name='add_reply'),
    path('courses/<int:course_id>/episode/<int:episode_id>/rewatch/', views.rewatch, name='rewatch'),
    path('download/<int:cert_id>', views.download_certificate_image, name='download_certificate_image'),
    path('retake/<int:course_id>',views.retake, name='retake_quiz'),
]