# Generated by Django 5.2.6 on 2025-10-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0003_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=10, null=True),
        ),
    ]
