# Generated by Django 5.2.6 on 2025-10-22 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0006_episodeprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeprogress',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ep_progress', to='piotechapp.episode'),
        ),
    ]
