# Generated by Django 5.2.6 on 2025-10-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0009_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='category',
            field=models.CharField(choices=[('EG', 'Engineering'), ('BC', 'Blockchain'), ('FD', 'Finance & Defi'), ('WD', 'Web Development'), ('DS', 'Data Science & AI'), ('UI', 'UI/UX Design'), ('CY', 'Cybersecurity'), ('OT', 'Other')], default='OT', max_length=3),
        ),
    ]
