# Generated by Django 5.2.6 on 2025-10-26 16:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0010_proposal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
