# Generated by Django 5.2.6 on 2025-10-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0011_course_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
