# Generated by Django 5.2.6 on 2025-11-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0012_alter_course_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='start_course',
            name='tx_hash',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
