# Generated by Django 5.2.6 on 2025-11-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0013_start_course_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete_course',
            name='tx_hash',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
