# Generated by Django 5.2.6 on 2025-11-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0014_complete_course_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete_course',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate/'),
        ),
        migrations.AddField(
            model_name='complete_course',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
