# Generated by Django 5.2.6 on 2025-11-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0015_complete_course_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='score',
            field=models.FloatField(default=70.0),
        ),
        migrations.AddField(
            model_name='episode',
            name='score',
            field=models.FloatField(default=70.0),
        ),
        migrations.AddField(
            model_name='episode',
            name='transcript',
            field=models.TextField(default='should be something'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='score',
            field=models.FloatField(default=70.0),
        ),
        migrations.AddField(
            model_name='proposalepisode',
            name='score',
            field=models.FloatField(default=70.0),
        ),
        migrations.AddField(
            model_name='proposalepisode',
            name='transcript',
            field=models.TextField(default='should be something'),
            preserve_default=False,
        ),
    ]
