# Generated by Django 5.2.6 on 2025-12-06 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0018_alter_complete_course_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_course', to='piotechapp.course'),
        ),
        migrations.AlterField(
            model_name='start_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_course', to='piotechapp.course'),
        ),
        migrations.AlterField(
            model_name='temp_quizscore',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piotechapp.course'),
        ),
    ]
