# Generated by Django 5.2.6 on 2025-12-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0024_exportsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete_course',
            name='token_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='complete_course',
            name='tx_hash',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
