# Generated by Django 5.2.6 on 2025-12-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0027_searched'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodeprogress',
            name='watched_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
