# Generated by Django 5.2.6 on 2025-12-27 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0028_episodeprogress_watched_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_doll', models.PositiveIntegerField(default=0)),
                ('reward', models.PositiveIntegerField(default=0)),
                ('reward_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piotechapp.course')),
            ],
        ),
    ]
