# Generated by Django 5.2.6 on 2025-12-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0029_course_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_reward',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course_reward',
            name='tx_hash',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
