# Generated by Django 5.2.6 on 2026-01-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0030_course_reward_sent_course_reward_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='revenue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
