# Generated by Django 5.2.6 on 2026-01-03 13:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0031_course_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
