# Generated by Django 5.2.6 on 2026-01-03 13:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0032_alter_course_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reward',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='course_reward',
            name='reward_doll',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
