# Generated by Django 5.2.6 on 2026-01-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piotechapp', '0033_alter_course_reward_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reward',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='piotechapp.course'),
        ),
    ]
